# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('name2', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.TextField()),
                ('reported_on', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=1024)),
                ('location', models.CharField(blank=True, max_length=1024, null=True)),
                ('notes', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemDescriptor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('img_url', models.CharField(blank=True, max_length=1024, null=True)),
                ('doc_url', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_from', models.DateTimeField()),
                ('reserved_until', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Item')),
                ('reserved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NetworkAnalyzer',
            fields=[
                ('itemdescriptor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ItemDescriptor')),
                ('freq_start', models.IntegerField(blank=True, null=True)),
                ('freq_stop', models.IntegerField(blank=True, null=True)),
            ],
            bases=('manager.itemdescriptor',),
        ),
        migrations.CreateModel(
            name='Oscilloscope',
            fields=[
                ('itemdescriptor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ItemDescriptor')),
                ('bw', models.IntegerField(blank=True, null=True)),
                ('samp_rate', models.IntegerField(blank=True, null=True)),
                ('num_chan', models.IntegerField(blank=True, null=True)),
            ],
            bases=('manager.itemdescriptor',),
        ),
        migrations.CreateModel(
            name='SignalGenerator',
            fields=[
                ('itemdescriptor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ItemDescriptor')),
                ('freq_start', models.IntegerField(blank=True, null=True)),
                ('freq_stop', models.IntegerField(blank=True, null=True)),
                ('output_power_max', models.IntegerField(blank=True, null=True)),
            ],
            bases=('manager.itemdescriptor',),
        ),
        migrations.CreateModel(
            name='SpectrumAnalyzer',
            fields=[
                ('itemdescriptor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ItemDescriptor')),
                ('freq_start', models.IntegerField(blank=True, null=True)),
                ('freq_stop', models.IntegerField(blank=True, null=True)),
                ('input_power_max', models.IntegerField(blank=True, null=True)),
            ],
            bases=('manager.itemdescriptor',),
        ),
        migrations.CreateModel(
            name='USRP_Daughterboard',
            fields=[
                ('itemdescriptor_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='manager.ItemDescriptor')),
                ('freq_start', models.IntegerField(blank=True, null=True)),
                ('freq_stop', models.IntegerField(blank=True, null=True)),
                ('output_power_max', models.IntegerField(blank=True, null=True)),
                ('input_power_max', models.IntegerField(blank=True, null=True)),
                ('bw_max', models.IntegerField(blank=True, null=True)),
            ],
            bases=('manager.itemdescriptor',),
        ),
        migrations.AddField(
            model_name='itemdescriptor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Category'),
        ),
        migrations.AddField(
            model_name='item',
            name='item_desc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.ItemDescriptor'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.Item'),
        ),
        migrations.AddField(
            model_name='errorreport',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
