# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-15 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name2',
        ),
    ]
